packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  prisma: true
  esbuild: true
  '@scarf/scarf': false
engineStrict: true
saveExact: true
autoInstallPeers: true
strictPeerDependencies: true
verifyDepsBeforeRun: error
